# -*- mode: python ; coding: utf-8 -*-

block_cipher = None

# PySide6 exclude modules
pyqt_exc = [
    'PySide6.QtNetwork',
    'PySide6.QtQml',
    'PySide6.QAxContainer',
    'PySide6.QtBluetooth',
    'PySide6.QtDBus',
    'PySide6.QtDesigner',
    'PySide6.QtHelp',
    'PySide6.QtMultimedia',
    'PySide6.QtMultimediaWidgets',
    'PySide6.QtNetworkAuth',
    'PySide6.QtNfc',
    'PySide6.QtOpenGL',
    'PySide6.QtPositioning',
    'PySide6.QtLocation',
    'PySide6.QtPrintSupport',
    'PySide6.QtQuick',
    'PySide6.QtQuick3D',
    'PySide6.QtQuickWidgets',
    'PySide6.QtRemoteObjects',
    'PySide6.QtSensors',
    'PySide6.QtSerialPort',
    'PySide6.QtSql',
    'PySide6.QtSvg',
    'PySide6.QtTest',
    'PySide6.QtTextToSpeech',
    'PySide6.QtWebChannel',
    'PySide6.QtWebSockets',
    'PySide6.QtWinExtras',
    'PySide6.QtXml',
    'PySide6.QtXmlPatterns'
]


a = Analysis(['DD监控室.py'],
             pathex=[],
             binaries=[],
             datas=[
                ('utils/ascii.txt', '.'),
                ('utils/help.html', '.'),
                ('utils/qdark.qss', 'utils'),
                ('utils/splash.jpg', 'utils'),
                ('utils/vtb.csv', 'utils'),
                ('scripts/run.bat', '.'),
             ],
             hiddenimports=[],
             hookspath=['hooks'],
             runtime_hooks=[],
             excludes=pyqt_exc,
             win_no_prefer_redirects=False,
             win_private_assemblies=False,
             cipher=block_cipher,
             noarchive=False)
pyz = PYZ(a.pure,
          a.zipped_data,
          cipher=block_cipher)
exe = EXE(pyz,
          a.scripts,
          [],
          exclude_binaries=True,
          name='DDMonitor',
          debug=False,
          bootloader_ignore_signals=False,
          strip=False,
          upx=False,
          icon='favicon.ico',
          console=False )
coll = COLLECT(exe,
               a.binaries,
               a.zipfiles,
               a.datas,
               strip=False,
               upx=False,
               upx_exclude=[],
               name='DDMonitor')
