# -*- mode: python ; coding: utf-8 -*-

block_cipher = None

# PySide2 exclude modules
pyqt_exc = [
    'PySide2.QtNetwork',
    'PySide2.QtQml',
    'PySide2.QAxContainer',
    'PySide2.QtBluetooth',
    'PySide2.QtDBus',
    'PySide2.QtDesigner',
    'PySide2.QtHelp',
    'PySide2.QtMultimedia',
    'PySide2.QtMultimediaWidgets',
    'PySide2.QtNetworkAuth',
    'PySide2.QtNfc',
    'PySide2.QtOpenGL',
    'PySide2.QtPositioning',
    'PySide2.QtLocation',
    'PySide2.QtPrintSupport',
    'PySide2.QtQuick',
    'PySide2.QtQuick3D',
    'PySide2.QtQuickWidgets',
    'PySide2.QtRemoteObjects',
    'PySide2.QtSensors',
    'PySide2.QtSerialPort',
    'PySide2.QtSql',
    'PySide2.QtSvg',
    'PySide2.QtTest',
    'PySide2.QtTextToSpeech',
    'PySide2.QtWebChannel',
    'PySide2.QtWebSockets',
    'PySide2.QtWinExtras',
    'PySide2.QtXml',
    'PySide2.QtXmlPatterns'
]


a = Analysis(['DD监控室.py'],
             pathex=[],
             binaries=[],
             datas=[
                ('utils/ascii.txt', '.'),
                ('utils/help.html', '.'),
                ('utils/qdark.qss', 'utils'),
                ('utils/splash.jpg', 'utils'),
                ('utils/vtb.csv', 'utils'),
                ('scripts/run.bat', '.'),
             ],
             hiddenimports=[],
             hookspath=['hooks'],
             runtime_hooks=[],
             excludes=pyqt_exc,
             win_no_prefer_redirects=False,
             win_private_assemblies=False,
             cipher=block_cipher,
             noarchive=False)
pyz = PYZ(a.pure,
          a.zipped_data,
          cipher=block_cipher)
exe = EXE(pyz,
          a.scripts,
          [],
          exclude_binaries=True,
          name='DDMonitor',
          debug=False,
          bootloader_ignore_signals=False,
          strip=False,
          upx=False,
          icon='favicon.ico',
          console=False )
coll = COLLECT(exe,
               a.binaries,
               a.zipfiles,
               a.datas,
               strip=False,
               upx=False,
               upx_exclude=[],
               name='DDMonitor')
